### PR TITLE
added decimal datatype

### PR DESCRIPTION
**Pull request by vecchiocarmelo**
added decimal datatype

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
@vecchiocarmelo updated the pull request.

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-4** [comment]
@vecchiocarmelo updated the pull request.

**Comment by onurfiliz** [comment]
@vecchiocarmelo thank you very much for your contribution. We need to extend a few test cases to make sure this data type is tested. I can dig those out if you prefer to extend them yourself. Otherwise we can merge as is and we will take care of it later on.

**Comment by onurfiliz** [comment]
@vecchiocarmelo thank you for your PR. This is also covered by #59, which is slightly more general so I merged that instead. I hope that's OK.

**Pull request closed without merging**
