### PR TITLE
Translate DECIMAL type to numeric rather than character in R 

### PR DESCRIPTION
**Pull request by jarodmeng**
We also modify tests, documentations, and vignettes accordingly.

### CODE REVIEW

**Comment by jarodmeng** [comment]
Fixing #162

**Comment by jarodmeng** [comment]
All unit tests passed and R CMD CHECK returns no error/warning/note.

**Comment by leepface** [comment]
Hmm... not sure about this one. It feels like there could be unintended behavior here. Based on https://prestodb.io/docs/current/language/types.html#decimal, depending on exact arguments, it could make more sense to bring this data in as integer (when scale is 0) and may make sense to bring it in as character if there's going to be a loss of precision (in the - admittedly rare - case where this is specified to 38 decimal places).

I think at a minimum we should have some more robust tests of edge cases across the range of scale and precision parameters.

**Comment by jarodmeng** [comment]
> Hmm... not sure about this one. It feels like there could be unintended behavior here. Based on https://prestodb.io/docs/current/language/types.html#decimal, depending on exact arguments, it could make more sense to bring this data in as integer (when scale is 0) and may make sense to bring it in as character if there's going to be a loss of precision (in the - admittedly rare - case where this is specified to 38 decimal places).
> 
> I think at a minimum we should have some more robust tests of edge cases across the range of scale and precision parameters.

Good point. I haven't tested the use case of DECIMAL to store precise large numbers (anything beyond the DOUBLE precision limit which is about 16 digits).

I actually haven't seen any usage of DECIMAL in real data yet, so it's hard to gauge how useful translating DECIMAL to numeric vs. character would be for real users. I will leave this issue open for now. If there are real use cases raised by users, we can revisit and craft a better solution then.

**Comment by leepface** [comment]
Sounds good. Let's leave it open for now.

**Pull request closed without merging**
