### PR TITLE
Add tests for new data types

### PR DESCRIPTION
**Pull request by cosinequanon**
Add tests for the new tinyint/smallint/integer/real data types that Presto now
has support for.

### CODE REVIEW

**Comment by spragues-trulia** [comment]
Hi guys,
Sorry but this is going to probably be a dumb question (given i know next to nothing about R) but i do know some things about Presto. I'm trying to help a colleague who is using RPresto against our version of Presto v0.160 and he's getting errors on the 'int' datatype. The error looks like this:


> res <- dbSendQuery(con, query)
> presto_test2 <- (dbFetch(res, -1))
Error in .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) : 
  Unsupported column type: NA


I've loaded the latest version of R and followed your install instructions for RPresto... and found this commit about testing the tinyint/int/real datatypes so it seems you know something about this issue. :)   

the question i have is how can i install this patch and test it out?   

and again apologies if this is a dumb question.

**Comment by cosinequanon** [comment]
Hey @spragues-trulia, you should be able to pull in integer/smallint/tinyint/real types with the latest version. The only Presto version not currently supported is the row type. I would verify that the query isn't trying to pull in the row type as it will cause the same error you are reporting.

Make sure you are pulling from github to get the latest, you can do this by running `devtools::install_github('prestodb/RPresto')` then I would verify you can run a simple query like `select cast(1 as integer)` which works for me on the latest.

**Comment by spragues-trulia** [comment]
hi @cosinequanon - ah i see.  D'oh! i was installing RPresto via the CRAN method. Maybe if i had read your docs better i would have seen that the other method shows how to install it from gitthub!  Thanks!  And thanks for the tip on the "row" type. something tells me we might encounter those but we'll see.  I'll confirm matters tomorrow! 
thanks again!

**Comment by spragues-trulia** [comment]
fyi.  everything works as advertised. thank you.

**Pull request merged**
